Argus-Labs/world-engine

cardinal/go.mod, cardinal/go.sum
Update cardinal's sign version
This change is a trivial rework / code cleanup without any test coverage.
=> chore(cardinal): Update cardinal's sign dependency

CODEOWNERS, game/sample_game/docker-compose.yml, game/sample_game/magefiles/main.go, game/sample_game/nakama/cardinal.go, game/sample_game/nakama/go.mod, game/sample_game/nakama/go.sum, game/sample_game/nakama/main.go, game/sample_game/nakama/private_key.go, game/sample_game/server/go.mod, game/sample_game/server/go.sum, game/sample_game/testsuite/Dockerfile, game/sample_game/testsuite/go.mod, game/sample_game/testsuite/go.sum, game/sample_game/testsuite/testsuite_test.go, game/sample_game/testsuite/util.go, go.work
Fixes NAK-4
Add integration tests to the Nakama/Sample Game package.
- Add a testsuite docker-compose target that depends on Nakama and the Sample game
- Add mage target that clears existing users from Nakama, and then runs the integration test
- Make a testsuite docker image.
- Added integration tests for end-to-end deployment with docker compose
=> feat(sample_game): integration tests for persona tag management

CODEOWNERS, cardinal/server/server_test.go
Closes: #XXX
> Add a description of the overall background and high-level changes that this PR introduces
_(E.g.: This pull request improves documation of area A by adding ...._
_(for example:)_
- _The metadata is stored in the blob store on job creation time as a persistent artifact_
- _Deployments RPC transmits only the blob storage reference_
- _Daemons retrieve the RPC data from the blob cache_
_(Please pick one of the following options)_
_(or)_
_(or)_
_(example:)_
- …
=> chore: update codeowners, skip flaky test

go.work, go.work.sum
=> chore(starter-game-template): fix go.work paths

cardinal/component.go
Add the RemoveFrom and AddTo function to the cardinal package. This allows users to change the components that exist on entities.
=> fix(cardinal): Add the AddTo and RemoveFrom functions to components

chain/cmd/world/cmd/root.go, chain/docker-compose.yml, chain/scripts/start-rollup.sh, chain/scripts/start.sh
fixes the help text for the chain CLI
fixes the script to remove all `world` chain data before running again.
=> fix(chain): world binary help text, script fixes

chain/scripts/start-rollup.sh
adds the lazy aggregator flag to start-rollup.sh script
above
n/a
=> chore(chain): lazy aggregator flag in start-rollup.sh script

cardinal/option.go
Add an cardinal.WorldOption wrapper for pretty logging.
Trivial change
=> feat(cardinal): Add pretty log wrapper for cardinal

cardinal/world.go
Closes: #WORLD-305
Super tiny this exposes CurrentTick in cardinal.World
Just added one method. 
This is probably too simple for a test.
=> feat(cardinal): expose current tick on cardinal.World.

cardinal/world.go
Closes: #world-296
exposes Tick in cardinal.World
See change. 
No tests. To small of a change.
=> feat(cardinal): expose Tick in cardinal.World

cardinal/server/health.go, cardinal/server/query.go, cardinal/server/server.go, cardinal/server/server_test.go, cardinal/server/swagger.yml
Closes: #world-350
Add a health endpoint to cardinal. This endpoint can be augmented in the future with more things. Should also mention this health endpoint is required for the CLI project.  
Added entry into swagger.
Added new health.go file
Added new test to server_test.go
=> feat(cardinal): add new health endpoint

cardinal/ecs/storage/engine.go, cardinal/ecs/storage/redis_storage.go, cardinal/ecs/storage/storage.go, cardinal/ecs/store/store.go, cardinal/ecs/world.go, cardinal/server/game_manager.go, cardinal/server/server_test.go
Closes: #WORLD-356
Expose closing of the client connection during shutdown. 
Added new Close() method to interfaces involving storage. 
adjusted tests to use shutdown.
=> feat(cardinal): expose close redis method. 

cardinal/component.go, cardinal/ecs/component.go, cardinal/ecs/ecs_test.go, cardinal/ecs/tick_test.go
Closes: #391
Change RemoveFrom and AddTo methods to functions. 
Rewrote tests that used these methods.
=> chore(cardinal): change removeFrom addto.

cardinal/ecs/persona.go
updates the authorizepersonaaddresssystem to use the tx iterator
_(for example:)_
- _The metadata is stored in the blob store on job creation time as a persistent artifact_
- _Deployments RPC transmits only the blob storage reference_
- _Daemons retrieve the RPC data from the blob cache_
_(Please pick one of the following options)_
_(or)_
_(or)_
_(example:)_
- _Extended integration test for ..._
- _Manually verified the change by ..._
=> refactor(cardinal): update AuthorizePersonaAddressSystem to use tx iterator

cardinal/ecs/transaction/transaction_test.go, cardinal/ecs/world_test.go
not sure why CI didn't catch this but some tests failed after merging router PR. this PR fixes that.
- fix 2 tests
test cardinal directory
=> fix(cardinal): update tests to use world context

cardinal/ecs/world.go, relay/nakama/dispatcher.go
Doesn't close anything this is an extremely minor fix. Some things weren't fully camel case, this fixes that.
=> fix(cardinal): make some json camelcase.

cardinal/server/swagger.yml, cardinal/transaction.go
Closes: #Does not close any ticket. 
fixes some bugs might unblock people so I'm making this PR early. 
fixes endless recursion bug. 
fixes swagger wrong reply struct.
=> fix(cardinal): fixes some misc bugs

cardinal/evm/server.go
=> chore(cardinal): add logs for whether or not cardinal's evm server is starting with credentials 

relay/nakama/dispatcher.go
fixes a json tag typo 
_(for example:)_
- _The metadata is stored in the blob store on job creation time as a persistent artifact_
- _Deployments RPC transmits only the blob storage reference_
- _Daemons retrieve the RPC data from the blob cache_
_(Please pick one of the following options)_
_(or)_
_(or)_
_(example:)_
- _Extended integration test for ..._
- _Manually verified the change by ..._
=> fix(relay): typo in json tag

relay/nakama/main.go
transaction notifications only need to be sent out when handling transactions. Other endpoints (e.g. queries) will not generate a tx receipt.
There's not currently a great way to run integration tests against relay/nakama. One way is to modify starter-game-template/docker-compse.yml. Under the `nakama` target, modify the `build:` line to point to this worl-engine/relay/nakama directory (instead of `./nakama`). then run `mage test` like normal.
=> fix(nakama): Skip tx notifications when hitting non-tx endpoints

.github/workflows/lint.yml
Closes: #XXX
> hot fix PR title linter
=> fix(ci): PR title linter only run on PR event

sign/sign.go, sign/sign_test.go
Closes: #world-522
Swagger endpoints process transaction bodies as a map[string]any{}. This object is JSON serialized which ends up sorting the JSON fields. If the original transaction signature was generated with a JSON body that did NOT have sorted fields, different hashes will be generated which will cause the signature verification to fail. 
This PR fixes signature generation so that unsorted JSON blobs are sorted before the hash is generated.
- _Added unit test that validates an unsorted JSON blob can be signed and verified.
=> fix(sign): Sort JSON blobs before signing them

cardinal/go.mod, cardinal/go.sum, go.work.sum, relay/nakama/go.mod, relay/nakama/go.sum
updates cardinal & nakama with new sign version that includes bugfix
=> chore: update sign deps for nakama & cardinal

cardinal/ecs/storage/redis_storage.go
Closes: WORLD-565
adds eris to ecs.storage
Info:
=> feat(cardinal): add eris to ecs storage.

cardinal/ecs/message.go, cardinal/ecs/persona.go, cardinal/ecs/query.go, cardinal/ecs/search.go, cardinal/ecs/tick_test.go, cardinal/ecs/world.go
adds eris to all files in the ecs folder. 
Info:
=> feat(cardinal): add eris to ecs files.

cardinal/ecs/ecb/active.go, cardinal/ecs/ecb/component.go, cardinal/ecs/ecb/ecb.go, cardinal/ecs/ecb/read_only.go, cardinal/ecs/ecb/redis.go, cardinal/ecs/ecb/tick.go, cardinal/ecs/tick_test.go
Closes: WORLD-562
add eris to ecs.ecb
This one is a lot of files but nothing too complex. I have a bunch of other PRs open that are much smaller. 
Info:
=> feat(cardinal): add eris to ecs ecb

cardinal/go.mod, cardinal/go.sum, cardinal/server/debug.go, cardinal/server/game_manager.go, cardinal/server/query.go, cardinal/server/server.go, cardinal/server/tx.go, cardinal/server/utils.go
Closes: WORLD-537
This adds eris to cardinal server. 
Info:
=> feat(cardinal): add eris to cardinal server

relay/nakama/allowlist.go
=> chore(relay): use invalidargument for bad beta keys.

relay/nakama/allowlist.go, relay/nakama/main.go
Closes: n/a
some left over raw errors from WORLD-572
=> chore(relay): finish returning errors with grpc codes from registered nakama RPCs

cardinal/events/events_test.go
Closes: WORLD-545
Test has a "race" condition. Just make a thread safe buffer. 
run this:
`go test ./... --run TestEventHubLogger --count=10 --race`
To confirm the race condition no longer exists
=> fix(cardinal): fix small race condition in test. 

cardinal/ecs/world.go
Closes: WORLD-544
Assumes Only one thread of `RecoverFromChain` is ever called. Race condition is extremely minor, I doubt it will even really occur as it's just a read operation that gets denied here.
=> fix(cardinal): race condition with recover

cardinal/server/game_manager.go, cardinal/server/option.go, cardinal/world.go
Closes: WORLD-622
This gets pretty printing working with server and game_manager. So if you set it for game_manager it will be set for everything. 
I maintain this level of granularity in case someone finds it good for testing, or in the future we want server and game_manager to own their own logger.
=> feat(cardinal): get pretty printing with server and game_manager. 

README.md, docs/pages/Cardinal/getting-started.mdx
update getting started docs, and readme
=> docs: update readme, docs for getting started

cardinal/ecs/world.go
Closes: WORLD-646
Add timers on all systems and flush in milliseconds.
=> feat(cardinal): add timing logs for all systems and flush.

cardinal/ecs/world.go
Closes: WORLD-649
self explanatory.
=> feat(cardinal): log amount of txs per click.

cardinal/README.md
Not using the README in /cardinal, so just removed it.
- Remove /cardinal/README.md
- N/A
=> chore: remove unused /cardinal README.md

cardinal/world_context.go
=> chore(cardinal): update comment on NewSearch

relay/nakama/allowlist/allowlist.go, relay/nakama/errors/errors.go, relay/nakama/handlers.go, relay/nakama/utils/nakama.go
Here's some sample code for how I was imagining the RPC handler.
=> refactor(nakama): four step pattern example for handlers

relay/nakama/cardinal.go
Minor requested changes from #577 that didn't get fixed before merge, a few lines only!
=> chore(nakama): minor requested changes

starter-game-template/README.md
=> docs: update README to use latest world cli commands

relay/nakama/persona/storage.go
Closes: WORLD-587
- `cardinalCollection` -> `cardinal_collection`
- `personaTag` -> `persona_tag`
=> refactor(nakama): change nakama storage object tags to snake case

cardinal/world_recovery.go
updates recover from chain so that it can recover from partial data loss. i.e. we somehow lost a chunk of our data on redis
=> refactor(cardinal): RecoverFromChain attempts to recover from current tick instead of 0

cardinal/world.go
=> refactor(cardinal): remove unused WorldStateType

cardinal/server/handler/tx.go, cardinal/server/server_test.go
Closes: WORLD-894
When signature verification is disabled, we should accept any and all transactions that come in. Previously, cardinal would complain if the persona tag of a transaction did not have a signer address. This PR modifies the code so that a persona tag's signer address is not checked at all when signature verification is disabled.
- Add tests demonstrating problem
- Fix the tests
2 unit tests were added.
=> fix(cardinal): Do not check signer address when signature verification is disabled

cardinal/search.go
Closes: WORLD-814
straight forward. See code changes.
=> chore(cardinal): get rid of mapped caches, just have one cache on search. 

cardinal/log/log_test.go, cardinal/plugin_persona.go
=> refactor(cardinal): rename registerpersonasystem to createpersonasystem to be more consistent. 

cardinal/server/docs/docs.go, cardinal/server/docs/swagger.json, cardinal/server/docs/swagger.yaml, cardinal/server/handler/world.go, cardinal/server/server.go, cardinal/server/server_test.go, cardinal/types/util.go
Add field information to components on `/debug/world` endpoint
- modify response from array of string to array of object contains :
-- component name
-- field information
- Adjust unit test
- Test run and got this response
```
{
"components": [
{
"name": "SignerComponent",
"fields": {
"AuthorizedAddresses": "[]string",
"PersonaTag": "string",
"SignerAddress": "string"
}
},
{
"name": "Playersssss",
"fields": {
"Nickname": "string"
}
},
{
"name": "asdsssssasd",
"fields": {
"HP": "int"
}
}
],
"messages": [
{
"name": "create-player",
"fields": {
"Nickname": "string"
}
},
{
"name": "attack-player",
"fields": {
"TargetNickname": "string"
}
},
{
"name": "create-persona",
"fields": {
"PersonaTag": "string",
"SignerAddress": "string"
}
},
{
"name": "authorize-persona-address", …
```
=> feat(cardinal): add field information to components in /debug/world endpoint

cardinal/plugin_persona.go
Found a small typo but I rephrased the err message a bit to be more clear
=> chore(cardinal): typo & rephrase persona tag character limit error message

cardinal/events/events.go, cardinal/events/events_test.go, cardinal/testutils/world.go
Closes: WORLD-939
- makes `RegisterConnection` and `UnregisterConnection` blocking. These functions will block until a websocket connection is finished and placed into eventHub
- Created blocking methods to read the amount of connections eventHub has and to read the amount of events in the eventHub queue. 
- Deleted ThreadSafeBuffer as it's unused. 
- Created new function NewTestFixtureWithPort. The reason why is because the random ports that is selected by the original Test fixture constructor could crash the test if run enough times. This is rare, I do not believe it happens often enough to show up on CI, but it did show up locally. 
- Fixed TestEvents
- Two bugs. The testfixture would sometimes use a port that was unavailable. This was fixed with NewTestFixtureWithPort. This bug is …
=> feat(cardinal): fix flakey tests with features in eventhub. 

cardinal/world.go
This PR inlines `world.emitResourcesWarning` since it is only used once and is fairly straightforward. Splitting it into separate makes it less readable and clutter the already complicate World struct.
- Inline `world.EmitResourcesWarning`
- N/A
=> refactor(cardinal): inline emitResourcesWarning

cardinal/server/handler/world.go
Closes: WORLD-915
Add message/query endpoints in /world payload
- add url field when returning messages and queries
Tested manually with result :
```
{
"components": [
{
"name": "SignerComponent",
"fields": {
"AuthorizedAddresses": "[]string",
"PersonaTag": "string",
"SignerAddress": "string"
}
},
{
"name": "Player",
"fields": {
"Nickname": "string"
}
},
{
"name": "Health",
"fields": {
"HP": "int"
}
}
],
"messages": [
{
"name": "create-persona",
"fields": {
"PersonaTag": "string",
"SignerAddress": "string"
},
"url": "/tx/persona/create-persona"
},
{
"name": "authorize-persona-address",
"fields": {
"Address": "string"
},
"url": "/tx/game/authorize-persona-address"
},
{
"name": "create-player",
"fields": {
"Nickname": "string"
},
"url": "/tx/game/create-player"
},
{
"name": "attack-player", …
```
=> feat: Add message/query endpoints in /world payload

docs/client/nakama/relay.mdx
Update some unity examples to match unity patterns.
=> docs(cardinal): Fix unity examples

e2e/tests/clients/nakama.go
Update the end to end test framework so that a websocket failure after the test is over does not result in a test failure.
To run end to end tests locally, run;
`make e2e-nakama` from the world-engine directory.
Alternatively, run nakama and cardinal with:
`docker comopse up nakama game --build` from the world-engine directory. Run the tests in `e2e/tests/nakama/...` via `go test` or from your IDE.
=> fix(carinal): Fix flaky test when websocket is closed normally

makefiles/test.mk
=> fix: swaggo dependency error

cardinal/server/handler/cql.go
=> fix(cardinal): remove C import

docs/client/nakama/relay.mdx
Fixing example code in the documentation
- Fixed Unity / C# example code on the Nakama "Game Engine/Client Integration" documentation page
n/a
=> docs(cardinal): fix Nakama integration example code

e2e/testgames/go.mod, e2e/testgames/go.sum, relay/nakama/auth/custom.go, relay/nakama/auth/siwe.go, relay/nakama/main.go
Closes: GDEV-1106
Add validation for SIWE in LinkCustom on nakama.
- Add validation for SIWE before triggering LinkCustom
- Covered by old unit test
Manually tested using nakama console
- Before link
- Link Request
- After Link
=> feat: link with ethereum on nakama

.github/workflows/test.yml, docker-compose.yml, e2e/tests/nakama/Dockerfile, evm/Dockerfile, evm/app/app.go, evm/go.mod, evm/go.sum, evm/scripts/app.toml, evm/scripts/config.toml, evm/scripts/start-celestia-devnet.sh, evm/scripts/start-sequencer.sh, evm/sequencer/server.go, evm/sequencer/server_test.go, evm/sequencer/tx_queue.go, evm/sequencer/tx_queue_test.go, go.work.sum, makefiles/start.mk, makefiles/test.mk
=> fix(evm): preblocker crash, load config from app.toml, rollkit sequencing

cardinal/cardinal_test.go, cardinal/engine_test.go, cardinal/router/mocks/router.go, cardinal/router/option.go, cardinal/router/router.go, cardinal/world.go, cardinal/world_recovery_test.go
=> feat: add jobqueue tracing

cardinal/config.go, cardinal/engine_test.go, cardinal/go.mod, cardinal/router/router.go, cardinal/server/server.go, cardinal/server/server_test.go, cardinal/storage/redis/storage.go, cardinal/telemetry/telemetry.go, cardinal/world.go, cardinal/world_fixture.go, cardinal/world_recovery.go, cardinal/world_recovery_test.go, cardinal/world_test.go, cardinal/worldstage/worldstage.go
This pull request refactors the logging mechanisms and shutdown procedures across various Cardinal components. Below are the major changes introduced:
1. **Logging Enhancements**:
- Improved log messages for clarity by adding more descriptive information.
- Added logging statements in the `world`, `router`, `server`, and `storage` packages to monitor lifecycle events closely.
2. **Graceful Shutdown**:
- Implemented graceful shutdown for the HTTP server using a context to handle the shutdown sequence, avoiding abrupt terminations.
- Added a shutdown timeout of 5 seconds to allow ongoing requests to complete.
3. **Refactoring**:
- Refactored the `shutdown` process in the `world` component to ensure all goroutines are properly shut down.
- Renamed internal functions like `RecoverFromChain` …
=> refactor(cardinal): improve shutdown handling
