cardinal/ecs/read.go
cardinal/server/server_test.go

before, read handlers were passed raw json bytes. this PR refactors so that serialization/deserialization happens before the read handler is called, allowing devs to operate on concrete request/reply types.
- add type parameters for request and reply types
- change read handler function to take in a request type, and return a reply type.
`server_test.go`
- Does this pull request introduce a new feature or user-facing behavior changes? (yes)
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?
- How is the feature or change documented? (not applicable / specification (`x/<module>/spec/`) / [Osmosis docs repo](https://github.com/osmosis-labs/docs) / not documented)

refactor(cardinal)!: inject request/reply types into read handlers

---

cardinal/ecs/world.go

Fixes: CAR-109
Cardinal users currently have to manually spin out a go routine that runs the game loop like so:
```go
go func() {
for range time.Tick(time.Second) {
if err := world.Tick(context.Background()); err != nil {
panic(err)
}
}
}
```
We should abstract this away and let the user pass in their preferred tick time, to something like this:
```go
world.StartTicks(ctx, time.Millisecond * 100)
```
- _Add a function called `StartTicks(ctx, loopInterval)` in `world.go` that would be called in the user's `main.go`_

feat: abstract game loop into world.StartTicks()

---

cardinal/ecs/receipt/receipt.go
cardinal/ecs/world.go
cardinal/server/handler.go
cardinal/server/receipt.go
cardinal/server/server.go
cardinal/server/server_test.go
cardinal/server/utils.go

…om cardinal; remove leading slahes from cardinal http endpoints
Closes: #CAR-135, #CAR-130
- Add an HTTP endpoint that will return a list of transactions that have been processed over a range of ticks. 
- Update the HTTP endpoints to NOT have a leading slash.
- Code refactor: read and tx handler definitions have been moved to the handler.go file. 
- Some functions have been moved to the util.go file.
- NOTE: handler.go's code has mainly been moved from server.go
- NOTE: receipt.go's code is new
- Unit tests added to verify ranges of ticks are returned correctly
- Uint tests added to verify transaction errors and results are returned from the receipt endpoint
- Calling http://localhost:3333/list/tx-endpoints should now list tx endpoints without leading slash
- Calling …

feat(cardinal): Implement an endpoint to read transaction receipts fr… CAR-130 CAR-135

---

cardinal/ecs/tests/world_test.go
cardinal/ecs/world.go

we have variadic functions for all our other register type methods, so adding one for systems.
- adds variadic AddSystems function
- changes the original AddSystem function to just call into AddSystems.
`cardinal/ecs/tests/world_test.go`

feat(cardinal): AddSystems function

---

cardinal/ecs/abi.go
cardinal/ecs/abi_test.go

previously the struct tag for *big.Int was `solidity`, but the issue isn't specific to solidity. this changes the tag to `evm` to be more general.
- change struct tag from `solidity` to `evm`
`cardinal/ecs/abi_test.go`

refactor(cardinal): change struct tag to evm to be more general

---

cardinal/ecs/component.go

Closes: #CAR-147
Remove SetValue from Cardinal in components.go. It is a redundant method to Set and it's not used anywhere. 
I just deleted the method. A very simple change. 
go test ./... in the ecs folder under cardinal yielded no issues.

chore(cardinal): remove redundant method Set value from ComponentType (CAR-147)

---

chain/scripts/start-rollup.sh

Closes: n/a
enables the API server via a sed command that edits the app.toml configuration
add sed command to start-rollup.sh that edits the app.toml configuration and sets enabled = true in the api section.
run the stack, you should see a log from polaris say the rpc is running at 8545

fix(chain): enable API server in startup script

---

cardinal/ecs/receipt/receipt.go
cardinal/ecs/world.go

The receiptHistory keeps track of receipts from previous ticks, and allowed for the querying of receipts from past ticks. It's important that the receiptHistory's tick is the same as the world's tick, so that when the user asks for receipts from a certain tick, the receiptHistory struct can find them.
If the World object loads some game state that is on a non-zero tick, the receiptHistory struct was never notified about this advanced tick, and would not be able to return accurate tx receipt data.
This PR ensures the receitHistory tick and the world tick are always in sync.
I intend to write a unit test to demonstrate this bug, but I want to merge this and make a tagged version of cardinal to unblock some people first.

fix(cardinal): update history to have the correct tick

---

sign/sign.go
sign/sign_test.go

I recently fixed a bug where spaces in a signed message would be removed during the json marshal/unmarshal process, resulting in a different hash after sending the message over the wire. To fix this issue, I ran the json through a marshal/unmarshal process before computing the hash.
It turns out there's a method in encoding/json called "Compact" which already "normalizes" the json, and it's 4x faster.
No functionality changes, just an overall speedup. Existing unit tests verify the code.

perf(sign): Use json.Compact instead of marshal/unmarshal

---

cardinal/evm/option.go
cardinal/evm/server.go
cardinal/server/server.go
cardinal/server/server_test.go
chain/shard/server.go

previously, evm server returned a proto generated interface, hiding the `Serve` method. this PR fixes that by making a new interface with the Serve method in it. 
it also adds a port option, port env var, and a default port if neither is set.
also changes usage of `panic` to `log.Fatal` in go routines, so the entire program crashes, instead of just the go-routine.
- add port options for evm_sever
- return an interface from evm_server
- change usage of panic to log.Fatal for go routines

fix: return interface from evm server package, port option

---

cardinal/ecs/abi.go
cardinal/ecs/abi_test.go
cardinal/ecs/read.go

Previously, EVMSupport would not work for structs that had another struct as fields. this PR adds support for that. there is one caveat however, due to quirks in the ABI implementation. The inner struct MUST have JSON struct tags with PascalCase of the field name. For example:
```go
type Foo struct {
HelloWorld uint64 `json:"HelloWorld"`
}
```
- add ABI support for struct fields in structs
`cardinal/ecs/abi_test.go`

feat(cardinal): add support for ABI generating structs with struct fields

---

cardinal/server/server.go
cardinal/server/server_test.go

Closes: #CAR-115 (hopefully)
Fix the flaky tests in cardinal/server. Two issues were identified:
1) http's ListenAndServe returns an error when the server is shut down, and Handler.Serve would log a fatal error when ListenAndServe returns an error. During tests, it is desirable to close the http sever to free up the port for other tests. This was causing log.Fatal to be called during tests, which would not run all future tests. *The fix:* Return an error from Handler.Serve and let the caller decide how to handle the error.
2) While startup up an http server is fast, it's not instantaneous. In tests, we start the server on a non-main goroutine, but there's no guarantee that the server would be ready to handle traffic once the test code on the main threat was reached. *The fix:* Create a …

fix(cardinal): fix flaky http tests

---

cardinal/ecs/abi.go
cardinal/ecs/abi_test.go
cardinal/ecs/read.go
cardinal/ecs/transaction.go

adds support for slices of structs in EVM supported txs/reads
- adds support for slices of structs in EVM supported txs/reads
- changes the way unpacked values are handled in ABI decodings. previously, we could set the TupleType and the ABI package would use this type with reflection to set values into. There was no obvious way to do this with embedded types, so i am instead abusing the fact that the ABI package implicitly adds json struct tags to their reflected built structs. this allows us to JSON marshal the unpacked interface and JSON unmarshal into the typed structs.
cd cardinal
go test ./...

feat(cardinal): support slices of structs in ABI generated types

---

.github/workflows/image-release.yaml
chain/README.md
chain/docker-compose.yml

Closes: #DEVOP-38
Add CI pipeline to upload `chain` docker image to a public GCP Artifact Registry, and add README instruction on how to run the prebuilt docker image.
- Add CI pipeline (`.github/workflows/image-release.yaml`) to build & release `chain` docker image to GCP Artifact Registry.
- Container registry format will look like this:
- latest tag: `us-docker.pkg.dev/argus-labs/world-engine/chain:latest`
- specific tag version: `us-docker.pkg.dev/argus-labs/world-engine/chain:0.1.0-alpha2`
- Docker images will be published on these two event:
- push on main --> publish `latest` tag
- tag event --> publish tag version (`0.1.0-alpha`, `0.1.1`, ...)
- Create a tag release from Github repository pages
- Wait for CI to finish the build & push the image to Artifact Registry
- Try to pull …

chore(ci): prebuilt chain/base_shard docker image release

---

.github/workflows/image-release.yaml

Closes: #XXX
- Fix tag format for releasing Docker Image, previously image was released on tag format `vX.X.X`. Now it will only trigger on tag format `<module>/vX.X.X`. Currently, only `chain` modules are released.

chore(ci): Fix Docker Image CI tag format from `vX.X.X` to `chain/vX.X.X`

---

cardinal/server/handler.go

fixes the styling of how we return errors, usually have them followed by colons, not commas

style(cardinal): make error followed by colon instead of comma

---

cardinal/server/server.go
cardinal/server/server_test.go

Closes: #world-298
Small bug for swagger dynamic routes returning 500 errors instead of 404 when you put in the wrong dynamic route. 
changed to return 404 instead of error for 2 specific cases. 
Added two unit tests to test for 404 status code for these specific routes:
`/query/game/<readType>`
`/tx/game/<txType>`

fix(cardinal): return 404 for dynamic routes. Added tests to cover this.

---

cardinal/ecs/cql/cql.go
cardinal/ecs/cql/cql_test.go
cardinal/ecs/storage/legacy_storage.go
cardinal/go.mod
cardinal/go.sum

Closes: #WORLD-109
Adds a parser for a dynamic component query language. The intention of this language is to be parsed into a LayoutFilter type. 
Also branch name is wrong. Please ignore this is referencing WORLD 300, 109 is the EPIC. 
`
!(EXACT(a, b) & EXACT(a)) | CONTAINS(b)
`
CQL stands for component query language. 
Added two files. cql.go and cql_test.go
cql.go generates a parser:  string -> AST
This expression was tested: 
`!(EXACT(a, b) & EXACT(a)) | CONTAINS(b)` it covers multiple functions contains and exact. It covers & and |. It also covers higher precedence with parenthesis and the NOT (!) operator.

feat(cardinal): create parser for component query language.

---

cardinal/component.go
cardinal/ecs/component.go
cardinal/ecs/component/components_test.go
cardinal/ecs/cql/cql_test.go
cardinal/ecs/ecs_test.go
cardinal/ecs/filter/filter_test.go
cardinal/ecs/log_test.go
cardinal/ecs/persona.go
cardinal/ecs/query_test.go
cardinal/ecs/state_test.go
cardinal/ecs/tick_test.go
cardinal/ecs/transaction/transaction_test.go
cardinal/ecs/world.go

Closes: #WORLD-299
Allow fetching component by name. 
Currently many tests don't utilize the component name, additionally names now have to be unique. 
This issue is worth a conversation about usage of component names. Right now component names live in code as types and don't really exist in run time. There is a property called "Names" but I don't know how often that's used as uniqueness and explicit naming isn't enforced. There is a bit of reflection to sometimes match the type name but this isn't enforced strictly either and the results aren't always unique. 
I'm putting this up as a PR for now. It could change depending on the conversation.
I think this is worth a bit of a conversation then writing a secondary issue on top of this. Will bring it up on next stand up then update this. …

feat(cardinal): fetch component by name.

---

magefiles/setup/setup.go

Closes: [#DEVOP-45](https://linear.app/arguslabs/issue/DEVOP-45/fix-ci-build-cache-on-world-engine-repo)
- Fix CI test issue: `exec: "ginkgo": executable file not found in $PATH"`. (for example this [job run](https://github.com/Argus-Labs/world-engine/actions/runs/6166740214/job/16736732832?pr=264))
- Previously, this CI test issues were intermittent because the old cache still had `ginkgo` executables, now it will always installed during magefiles setup.
- Bring back `ginkgo` package for foundry to install during magefiles setup
- Run CI `testunitcover` job

chore(ci): fix test dependency - ginkgo

---

cardinal/ecs/tick_test.go
cardinal/ecs/world.go

Closes: #WORLD-308
Additional logging during a system panic
Added a recovery function that will log current system name and tick number, before forwarding the panic. 
Added a test to tick_test.go

feat(cardinal): create additional context for panics in logging. 

---

cardinal/ecs/query.go
cardinal/ecs/world.go

Closes: #WORLD-319 and #WORLD-129
Remove StorageAccessor. It's just a wrapper around a subset of the world.store field. 
As we continue with refactoring the ECS/storage packages it will be important to know when we require the ecs.World object when when we require a storage object. This PR makes that requirement more clear.
Existing tests will verify no functionality has changed.

refactor(cardinal): Remove StorageAccessor

---

cardinal/ecs/chain_recover_test.go
cardinal/ecs/ecs_test.go
cardinal/ecs/log_test.go
cardinal/ecs/persona.go
cardinal/ecs/query.go
cardinal/ecs/state_test.go
cardinal/ecs/storage/engine.go
cardinal/ecs/storage/redis_storage.go
cardinal/ecs/storage/redis_test.go
cardinal/ecs/system.go
cardinal/ecs/tick_test.go
cardinal/ecs/transaction.go
cardinal/ecs/transaction/transaction.go
cardinal/ecs/transaction/transaction_test.go
cardinal/ecs/world.go
cardinal/ecs/world_test.go
cardinal/evm/server_test.go
cardinal/server/server_test.go
cardinal/transaction.go
cardinal/world.go

Closes: #WORLD-318
Move the TransactionQueue struct out of the ecs package. We want to reduce the number of places that need to depend on the ecs package.
This touches a lot of files, but most of them are just `s/ecs.TransactionQueue/transaction.TxQueue`. 
Existing tests verify there are no functional changes.

refactor(cardinal): move tx queue out of ecs

---

docs/pages/Cardinal/API-Reference/cql.mdx

Closes: #XXX
- Fix docs MDX syntax error
```
./pages/Cardinal/API-Reference/cql.mdx
Could not parse import/exports with acorn: SyntaxError: Unexpected token
Import trace for requested module:
./pages/Cardinal/API-Reference/cql.mdx
```
-  add new line after `import Link from 'next/link'`

fix(docs): fix MDX syntax error (new line)

---

cardinal/server/server.go
cardinal/server/server_test.go
cardinal/world.go

Closes: #WORLD-317
Added new route /query/game/cql for the endpoint route.
Used some macro library to embedd the swagger.yml into the library so it doesn't have to be referenced by path. 
Replaced NewHandler with the swagger definition and retitled the old definition to OldHandler
When this is approved I will tag this with a new version and use it in the starter-template. 
ran go test ./... in cardinal.

feat(cardinal): prepare swagger routes for starter-template

---

cardinal/ecs/component/component.go
cardinal/ecs/ecs_test.go
cardinal/ecs/filter/filter_test.go
cardinal/ecs/log.go
cardinal/ecs/log_test.go
cardinal/ecs/storage/entity.go
cardinal/ecs/storage/layout.go
cardinal/ecs/store_manager.go
cardinal/ecs/world.go
cardinal/log.go
cardinal/server/server.go

Closes: #WORLD-321
- Finish removing the WorldAccessor interface
- Move move the Create/Remove code for entities into the store_manager.go source file.
- Make an alternative way to check if a component is in a slice of components. This is a preparation step for the eventual removal of the Layout struct.
Existing unit tests verify that there are no functional changes.

refactor(cardinal): Finish removing the WorldAccessor interface

---

cardinal/ecs/codec/codec.go
cardinal/ecs/component.go
cardinal/ecs/component/components_test.go
cardinal/ecs/storage/archetype.go
cardinal/ecs/storage/legacy_storage.go
cardinal/ecs/storage/legacy_storage_test.go
cardinal/ecs/storage/location_map.go
cardinal/ecs/storage/mock.go
cardinal/ecs/storage/redis_storage.go
cardinal/ecs/storage/redis_test.go
cardinal/ecs/transaction.go

Create a codec package to contain our Encode and Decode code. There no reason this needs to be in storage, and we break up storage into different packages, we want those other packages to easily be able to use Encode and Decode.

refactor(cardinal): Move encode and decode out of storage and into a codec package

---

chain/Dockerfile
chain/README.md
chain/app/app.go
chain/app/plugins.go
chain/precompile/router/router_test.go
chain/shard/option.go
chain/shard/server.go
chain/shard/server_test.go

streamlines the shard sequencer code, and adds light documentation about the two main rollup features.
- simplifies the shard sequencer server, by using a default port instead of requiring one to be explicitly set.
- changes shard handler server to `Sequencer` to be more specific about what this component does
- updates some comments
- add light explainer for the two custom features of the rollup chain
_(Please pick one of the following options)_
_(or)_
_(or)_
_(example:)_
- …

refactor(chain): defaults for shard sequencer

---

cardinal/cardinal_test.go
cardinal/ecs/world.go
cardinal/option.go
cardinal/server/server_test.go
cardinal/world.go

Closes: #WORLD-306
- Verify that a Query can be called inside of a cardinal based system (without needing the ecs package).
- Add a mechanism to manually start ticks, and be notified when ticks are completed.
- remove some code that was causing a for loop to unnecessarily spin.
Added a test to the cardinal package to demonstrate the usage of Query inside a system, as well as the new mechanism for starting a tick and blocking until the tick is done.

feat(cardinal): Add ability to be notified when a tick has finished

---

cardinal/cardinal_test.go
cardinal/component.go
cardinal/log.go
cardinal/query.go
cardinal/read.go
cardinal/server/game_manager.go
cardinal/server/server_test.go
cardinal/transaction.go
cardinal/world.go
go.work

Closes: #WORLD-358
Move game manager into cardinal.world so that cardinal.world now has the ability to shutdown. 
- renamed impl to implWorld, because now cardinal.world will own a server, gameManager and the ecs.World. A name like impl doesn't give any information about what that variable is and is even more ambiguose with cardinal.World owning other entities. 
- added a method IsGameRunning for aspects of our library and the user to detect if the game is already running. Game will not start if a game is already running. Just a note here, this method is NOT only used it tests. This method IS used before starting the game. 
- had to duplicate a utility function setTestTimeout. This is technical debt that will need to be handled in another ticket which I commented on here: …

feat(cardinal): cardinal.world now owns GameManager

---

cardinal/ecs/transaction.go
cardinal/ecs/transaction_test.go

Closes: #WORLD-365
Add an ability to loop over a number of transactions, and using the returned result/error to set the transaction receipts result/error.
Unit test added

feat(cardinal): allow for looping over transactions

---

.github/workflows/image-release.yaml
relay/nakama/Dockerfile

Closes: #WORLD-381
- Setup docker image CI deployment for Nakama
- Add CI workflow to build & release Nakama container images to public registry.
- on push to `main`: publish `us-docker.pkg.dev/argus-labs/world-engine/relay/nakama:latest`
- on tag `relay/nakama/v0.0.0`: publish `us-docker.pkg.dev/argus-labs/world-engine/relay/nakama:v0.0.0`
- trigger the CI by using tag `relay/nakama:v0.0.0` or push to `main` branch.
- CI run example: [[run-6498124375]](https://github.com/Argus-Labs/world-engine/actions/runs/6498124375)

chore(ci): publish relay/nakama container images

---

cardinal/go.mod
cardinal/server/events.go
cardinal/server/server_test.go

Closes: #402
Preliminary boostrap work and testing for web-socket library that will be used make an event route. 
> Add a description of the overall background and high-level changes that this PR introduces
Adds a test Websocket echo handler.
new events.go file. 
In that file is a websocket event handler. 
Refactored testHandler to be able to create Websocket routes and http routes. 
Added new test that tests the echo handler.

feat(cardinal): create events file. test websocket library.

---

cardinal/ecs/benchmark/benchmark_test.go
cardinal/ecs/ecb/doc.go
cardinal/ecs/ecb/ecb.go
cardinal/ecs/ecb/keys.go
cardinal/ecs/ecb/redis.go
cardinal/ecs/ecb/tick.go
cardinal/ecs/ecs_test.go
cardinal/ecs/internal/testutil/testutil.go
cardinal/ecs/log/log.go
cardinal/ecs/log/log_test.go
cardinal/ecs/mock_world.go
cardinal/ecs/store/store.go
cardinal/ecs/transaction/transaction_test.go
cardinal/ecs/world.go
cardinal/log.go
cardinal/world.go

Closes: #WORLD-384, WORLD-385
- Update all tests to use the ecb version of the storage manager.
- Update the log code to not depend on component indices (component indices are not used for ecb).
- Add tick management to the ecb (this is required because the tick increment must happen atomically with all other state changes)
- Update the World.Tick code to use ecb for tick starting, tick finalizing, and tick recovery.
- Add some benchmarks for track how long it takes to perform a world tick.
Existing unit tests verify that there are no functional changes by changing to this new data storage model.
To run the new benchmarks, go to world-engine/cardinal/ecs/ecb and run:
```
go test -bench=.
```

feat(cardinal): ecb for entity management

---

cardinal/ecs/component/components_test.go
cardinal/ecs/world.go

Closes: #411
> Add a description of the overall background and high-level changes that this PR introduces
New function partner to `RegisterComponent` called `MustRegisterComponent` that panics. 
Changed one test to use the new function.

feat(cardinal): new MustReg function

---

cardinal/ecs/abi/abi.go
cardinal/ecs/abi/abi_test.go
cardinal/ecs/query.go
cardinal/ecs/transaction.go

Closes: #422
Move abi.go into it's own  package.
abi.go and abi_test.go moved.
all original tests work.

refactor(cardinal): move abi.go and abi_test.go out of ecs and into an abi package. 

---

cardinal/cardinal_test.go
cardinal/events/events.go
cardinal/events/events_test.go
cardinal/server/events.go
cardinal/server/server_test.go
cardinal/test_utils/test_utils.go

Closes: #425
Added Event queueing to the hub with events getting broadcasted on calling the Flush method. 
Additionally moved Events.go from Server to an events package. 
Created a test_utils package on the side for shared functionality among tests. 
See above.
events are processed vertically. Meaning one thread per connection operating on the entire event queue during the flush. Each event in the queue is processed serially per connection.  
moved the events related tests from server_test to events package which necessitated the creation of the test_utils package.

feat(cardinal): event queueing and events package. 

---

cardinal/transaction.go

Closes: WORLD-441
- We need to expose ForEach on cardinal.TransactionType so users can use the Tx Iterator functionality via Cardinal and without ecs.
We are ignoring tests related to `cardinal.World` for the time being. [redacted] is the test.

chore(cardinal): expose ForEach on cardinal.TransactionType

---

cardinal/ecs/world.go
cardinal/transaction.go

Closes: WORLD-431
We are ignoring the fact that we don't have great tests for `cardinal.World` for the time being.

chore(cardinal): expose AddToQueue in Cardinal 

---

cardinal/ecs/options.go
cardinal/ecs/world.go
cardinal/events/events.go
cardinal/events/events_test.go
cardinal/test_utils/test_utils.go
cardinal/world.go

Closes: #439
Adds a new EventHub to the engine. 
EventHub has been changed to WebSocketEventHub and now an Interface called EventHub has replaced its existence in ecs.world. 
Fixed a subtle race condition bug involving OOM. See EmitEvent and FlushEvents. removed go routines. 
Created new option called WithLoggingEventHub allowing us to inject in a EventHubLogger
Changed EventHub to WebSocketEventHub
Created New interface called EventHub
Created New LoggingEventHub
Event broadcasting and event flushing were sent to go routines This could actually cause a memory leak where the game loop spun faster than the EventHub loop. If this occured the go routines would pile up as the game loop would emit events faster than the EventHub loop could handle it, thus blocked go routines will slowly …

feat(cardinal): logger event hub

---

cardinal/example_transactiontype_test.go
cardinal/transaction.go

Doesn't close any tickets. We missed a couple of methods for worldContext.

chore(cardinal): make these methods use wCtx.

---

cardinal/cardinal_test.go
cardinal/component_test.go
cardinal/ecs/mock_world.go
cardinal/evm/server.go
cardinal/query.go
cardinal/query_test.go
cardinal/search_test.go
cardinal/system_test.go
cardinal/test_utils/test_utils.go
cardinal/testing.go
cardinal/transaction_test.go
cardinal/world.go
cardinal/world_context.go

Add test files to the cardinal package to demonstrate how to test various features of cardinal (and to test the cardinal package itself).
There are two aspects of this PR that I'd like some specific feedback on:
1) The new private method in test_utils called "uniqueSignature" is lifted directly from `world-engine/cardinal/ecs/internal/testutil`. Should this internal testutil package get lifted out into a common area?
2) In test_utils.AddTransactionToWorldByAnyTransaction I have 2 methods for converting an externally facing *cardinal.World into an internal *ecs.World. Do you all have a preference? I'd prefer to keep it so the cardinal godoc package does not list any TestOnly methods, but the resulting pattern for accessing the data is a little weird.
- Updated ecs code to allow for the …

test(cardinal): Add test samples to cardinal package and extend test_utils package

---

cardinal/world.go

alas, the age old bug you cant avoid. golang re-uses pointers for loop variables, thus we end up registering the same system over and over and over and over...

fix(cardinal): fix register systems bug

---

cardinal/ecs/world.go
cardinal/log_test.go
cardinal/world.go

Closes: #WORLD-425
Ensure systems registered via the cardinal package include the function name in logs.
Added unit test to verify the log lines generated in systems contain the system name.

fix(cardinal): Ensure system logs in cardinal contain the system name

---

cardinal/ecs/world.go

Closes: #WORLD-448
Remove the unused TxBatch struct

refactor(cardinal): Remove the unused TxBatch struct

---

cardinal/ecs/query.go
cardinal/ecs/query_test.go
cardinal/ecs/transaction.go
cardinal/ecs/transaction/transaction_test.go

adds panics on empty arguments to tx and queries
- add panic for empty name and handler on queries
- add panic for empty name on txs
- change interface guards for tx and qs
- add tests
unit tests for query and txs

feat(cardinal): add panics for transactions and queries with empty args (WORLD-135, WORLD-134)

---

cardinal/test_utils/test_utils.go

Closes WORLD-458
- Edit the `MakeWorldAndTicker` function to accept variadic `WorldOption`s so that I can feed it options like ReceiptHistory size and such.
This change is already covered by existing tests.

chore(cardinal): MakeWorldAndTicker accepts options

---

cardinal/world.go

fix(cardinal): redundant server registration overriding event route.  

---

relay/nakama/events.go
relay/nakama/main.go

Closes: #464
reuse and rename methods such that it will satisfy a linter that will be added in another PR. 
mostly involves Unsubscribe and Shutdown methods inside the nakama eventHub.

refactor(relay): use event hub methods

---

internal/e2e/tester/cardinal/main.go

Closes: DEVOP-92
- Add CLIENT_CERT_PATH on Shard Sequencer (`shard.NewAdapter`) for e2e tester.
- CLIENT_CERT_PATH values =  path of chain/base-shard server SSL CA certs
- Run the docker compose services using SSL env variable option to enable secure connection.
- Run `go test -v` on `world-engine/internal/e2e` directory.

fix(internal): add CLIENT_CERT_PATH for e2e shard squencer client tester

---

test.mk

adds unit test commands to makefile.
try it out:
make unit-test cardinal
make unit-test chain
make unit-test-all
adds unit test commands to makefile
see above
_(example:)_
- _Extended integration test for ..._
- _Manually verified the change by ..._

feat: add unit-test commands to makefile

---

cardinal/ecs/transaction.go

adds an error log for when systems using tx iterators return an error in the iterator.
- add log
ran existing test:
```
{"level":"error","system":"ecs_test.TestForEachTransaction.func1","error":"some error","time":"2023-11-01T15:57:57-07:00","message":"tx 0x43fdd7497422eacb6f8af0cf70cabeeb1589190b777e4ca03b3a4db34dbde381 from some-persona-tag encountered an error with tx={GenerateError:true}"}
```

chore(cardinal): add log for iterated txs that encounter an error

---

cardinal/component_test.go
cardinal/transaction.go
cardinal/transaction_test.go

Closes: #490
A bunch of tests for more coverage of transaction. 
Removed 
type TransactionQueue struct {
_ *transaction.TxQueue
}
Seems to never be used.

test(cardinal): test coverage for api protection cardinal transaction.go

---

chain.mk
docker-compose.yml
relay/nakama/allowlist.go
relay/nakama/main.go

adds back the allowlist module that was previously only present in DF backend's fork of nakama.
manually

feat(relay): add back allowlist module

---

cardinal/ecs/filter.go
cardinal/ecs/filter/all.go
cardinal/ecs/filter/filter_test.go
cardinal/filter.go
cardinal/search_test.go
cardinal/server/debug.go
cardinal/server/server.go
cardinal/server/server_test.go
cardinal/server/swagger.yml
cardinal/testutils/test_utils.go

Closes: #503
Added a new filter called `All` This filter lives alongside `And` `Or` `Contains` and `Exact`. 
This filter is axiomatic meaning it is like `Contains` or `Exact` in that it is not constructed as a composition of other filters. 
`All` contains no components it simply matches true for every thing. 
in the future this new feature can be extended to CQL. 
Added a new route:
`/debug/state` that will do a search query using the All filter. 
Added a unit test on ecs.Search.
Added a integration test on the route `/debug/state`.

feat(cardinal): create debug endpoint that lists all entities in the game

---

makefiles/build.mk

adds `go mod vendor` to test game/nakama start make script.

chore: add `go mod vendor` to test game/nakama start script

---

cardinal/cardinal_test.go
cardinal/ecs/world.go
cardinal/world.go

Closes: #528
Allows the developer to register a system for initialization. Sort of like a constructor. 
This replaces world.Init which would just run a function in the context of worldContet. When you used the old world.Init before starting the game loop it could trigger an error if entities were created. 
By default registered init system will do nothing.
Modified some tests to check for stuff. 
Renamed the old init to `RunInContextOfWorldContext`
Made new `Init` function that registers a "constructor" system only at tick 0.

feat(cardinal): create new init system.

---

cardinal/ecs/world.go
cardinal/ecs/world_test.go
cardinal/evm/server_test.go

Closes: #WORLD-430
Update the WaitForNextTick method to use channels to block until a tick has completed. Remove the timeout path.
The TestServer_SendMessage test has also been refactors. The SendMessage method waits until a tick has completed before returning, which means it wouldn't be possible to call SendMessage 5 times to queue up 5 messages in the same tick. The test has been refactored so the SendMessage calls happen sequentially across multiple ticks.
This is OK in production, because a separate goroutine will be handling each SendMessage call. 
- Added unit test that validates the WaitForNextTick will block until a tick has completed, and will NOT block if the world has been shut down.

feat(cardinal): WaitForNextTick blocks until a tick has been completed

---

docker-compose.yml
makefiles/build.mk

Closes: #DEVOP-112 #DEVOP-113
> 
- Nakama doesn't officially support Postgres (see https://heroiclabs.com/docs/nakama/getting-started/install/linux/#cockroachdb), it's for development environments only.
- We should switch it to CockroachDB which is officially supported and with queries optimized for its storage engine.
- _Change Docker Compose setup to use CockroachDB for development (Single-node clusters)_
- _Fix makefile_
- _Use $DB_PASSWORD as env variable instead of plain text, the default value is "development"._
- This change is covered by existing E2E tests.

chore(db): replace Nakama PostgresDB with CockroachDB

---

cardinal/ecs/codec/codec.go
cardinal/ecs/codec/codec_test.go
cardinal/go.mod
cardinal/go.sum

Closes: #XXX
> Add a description of the overall background and high-level changes that this PR introduces
Our current codec is unoptimized. It uses the stdlib json that have low hanging performance improvement. We also used an encoder unnecessarily when we could just use marshal/unmarshal, leading to an additional object allocation.
By doing this, we are able to significantly speed up the codec while reducing memory foot print. See benchmark results below 
**Before**
```
goos: darwin
goarch: arm64
pkg: pkg.world.dev/world-engine/cardinal/ecs/codec
BenchmarkDecode
BenchmarkDecode       	 1786486	       710.6 ns/op	    1056 B/op	      10 allocs/op
BenchmarkDecode-5     	 1998490	       597.9 ns/op	    1056 B/op	      10 allocs/op
BenchmarkDecode-10    	 2008329	       592.2 ns/op	    1056 …
```

perf: improve codec performance

---

cardinal/cardinal_test.go
cardinal/ecs/persona.go
cardinal/ecs/world.go
cardinal/events/events.go
cardinal/gamestage/gamestage.go
cardinal/gamestage/gamestage_test.go
cardinal/world.go

Closes: WORLD-546
Fix some race conditions and shutdown sequencing.
- Shorten the sleep duration while waiting for the World to shut down
- Change the ecs.World tick into an atomic unit64
- Add the concept of a game sequence to cardinal to help with the starting and stopping of the game
Run `go test --count=10 --race` from the cardinal package and the ecs package to verify there are no race conditions. 
The server and events packages still have race conditions.

fix(cardinal): startup and shutdown race conditions

---

Makefile
makefiles/build.mk
relay/nakama/allowlist.go
relay/nakama/main.go

makes requests to claim-key all uppercase, so the casing no longer matters when claiming a key.
fixes an issue where you couldn't claim a tag after sending a request that was marked as rejected.
manually

fix(relay): make allowlist force requests to upper, and pass case where a persona tag was rejected when claiming (WORLD-556)

---

cardinal/events/events.go
cardinal/events/events_test.go
cardinal/go.mod
cardinal/go.sum

Closes: WORLD-536
This is a first PR of many that will eventually convert world-engine to use errors from this package:
https://github.com/rotisserie/eris
For the first part I just chose a really tiny use case to get a feel for the library. EventHub does not really create many custom errors. 
One drawback is that errors instantiated from other libraries or packages will not have stack traces. As soon as these errors touch our ecosystem we will have to wrap the errors with `erin.Wrap(err, "")` We can add additional error messages in place of the empty string. 
New errors …

feat(cardinal): add eris (errors with stacktraces) to eventhub

---

relay/nakama/allowlist.go
relay/nakama/cardinal.go
relay/nakama/dispatcher.go
relay/nakama/events.go
relay/nakama/go.mod
relay/nakama/go.sum
relay/nakama/main.go
relay/nakama/match.go
relay/nakama/notifications.go
relay/nakama/persona_tag_storage.go
relay/nakama/persona_tag_verifier.go
relay/nakama/private_key.go

Closes: WORLD-552
This adds eris to nakama. 
It's rather big. I have a bunch of other PRs that are smaller.
There are two functions that were changed. logError and logCode. Modified to take into account how errors can store stack traces. The reason is because these functions actually swallowed errors and created new ones from strings, so the new paradigm of errors with stack traces would get the stack erased. 
Info:

feat(cardinal): change entire nakama package to use eris.

---

cardinal/ecs/codec/codec.go

Closes: WORLD-558
Adds eris to codec.go
Info:

feat(cardinal): add eris to codec.go

---

cardinal/shard/adapter.go
cardinal/shard/option.go

Closes: WORLD-551
Small just changes to use eris for cardinal.shard
Info:

feat(cardinal): changed shard to work with eris.

---

cardinal/ecs/receipt/receipt.go
cardinal/ecs/receipt/receipt_test.go

Closes: WORLD-563
Adds eris to ecs.receipt
Info:

feat(cardinal): add eris to ecs receipt

---

cardinal/ecs/component/component.go
cardinal/ecs/component/metadata/component_metadata.go

Closes: WORLD-559
add eris to ecs.component
Info:

feat(cardinal): add eris to ecs component

---

relay/nakama/allowlist.go
relay/nakama/main.go

it seems that returning raw errors, instead of using nakama's `runtime.NewError` will cause the server to reply with a 500, this in turn makes the javascript code in WebGL implode. not good!

fix(relay): make claim-key use logCode instead of returning raw errors

---

cardinal/ecs/message.go
cardinal/ecs/message_test.go
cardinal/ecs/persona.go
cardinal/ecs/world_test.go
cardinal/example_messagetype_test.go
cardinal/message.go
cardinal/message_test.go

Closes: WORLD-542
Rename the message iterator to Each to match the search iterator
No functional changes

refactor(cardinal): Rename message ForEach to Each to match search iterator

---

cardinal/events/events.go
cardinal/server/server_test.go

Closes: WORLD-582
Basically to correctly close a websocket connection from the client side you must send it a close message. 
I moved the websocket test but there is a change to it. I send an additional close message before closing the dialer. 
This does not prevent an error from happening on the server side. The server still generates an error but with error code 1000 which indicates "normal closure" I check for this and swallow the error if it's normal.

fix(cardinal): fix panic bug in websocket test. 

---

relay/nakama/main.go

fixes an issue of trying to log a nil error, which in turn calls `err.Error()`

fix(relay): remove panic condition

---

assert/assert.go

Closes: WORLD-129
The new extra method on T getting called essentially "marks" the current context as the Test function and the assertion message will thus mark the correct line. The inner function calls the same method but for each test the first time this is called permanently marks that context as the assertion function and subsequent calls are ignored.

fix(cardinal): get correct line in asserts. 

---

cardinal/ecs/internal/testutil/testutil.go
cardinal/ecs/persona.go
cardinal/ecs/persona_integration_test.go
cardinal/ecs/persona_test.go
cardinal/evm/server_test.go
cardinal/testutils/testutils.go
internal/nakama/testsuite_test.go

Closes: WORLD-613
Add some extra validation around persona tags and eth addresses in the `RegisterPersonaSystem` and the `AuthorizePersonaSystem`
- Added two tests in `persona_integration_test.go` to test that invalid persona tags and invalid eth addresses are not accepted.

feat(cardinal): validation and error handling for register and auth persona

---

.github/workflows/lint-go.yml
.github/workflows/release.yaml

Closes: DEVOP-117 & DEVOP-137
CI improvement.
- Improve go lint caches dependency.
- EVM & Nakama container image release on the main branch will only be triggered if there are changes in the relevant directories.
- CI runs as intended

ci: improvement - golangci-lint cache & release image only when there are relevant file changes

---

docs/pages/Cardinal/_meta.json
docs/pages/Cardinal/persona-tags.mdx

Closes: WORLD-625
Add a section to the Cardinal docs covering Persona Tag. 
There's also a section in the Nakama docs about Persona Tags, however that section focuses on how Nakama sends Persona Tag requests to Cardinal.
Doc changes only; no tests.

docs(cardinal): Add persona tag section to docs

---

cardinal/ecs/log/log_test.go
cardinal/ecs/world.go

Closes: WORLD-619
Make completion execution print in info instead

feat(cardinal): have tick execution time always get printed.

---

evm/app/app.go

appication logger seemed to stop working.

fix(evm): switch from cosmos logger to zerolog

---

evm/scripts/start-sequencer.sh

removes hard coding of eth balance setting, uses FAUCET_ADDR instead.

fix(evm): use FAUCET_ADDR env var to inject eth balance

---

evm/app/app.go
evm/scripts/start-sequencer.sh

fix(evm): injects faucet_addr

---

CHANGELOG.MD

adds the changelog. @Argus-Labs/architects are expected to append to this when PR's that fall under any of the listed categories in the sections of the changelog.

chore: changelog

---

relay/nakama/main.go

switches the log level to debug for ErrNotAllowListed in ClaimPersona RPC.
additionally fixes a bunch of issues where we may have been attempting to return nil errors. this should fix issues where clients were seeing the error message set to "0065nil0065" or something to that effect.

fix(relay): fill in missing errors and switch error -> debug for some

---

relay/nakama/dispatcher.go

Remove the spammy logs that report when a receipt is not delivered to a client.
Note: This could instead be made into a debug log instead of removing the log entirely.
Trivial change

refactor(nakama): Remove the info logs when a receipt is not delivered to a client

---

relay/nakama/allowlist.go

1) When a user tries to claim a beta key that is already used, log the user and beta key
2) When a user tries to claim a beta key, but they've already claimed a beta key, include a non-nil error so the resulting logs have more details.
Logging changes only

refactor(nakama): Better logging for beta key claiming and verification

---

cardinal/ecs/ecb/tick.go
cardinal/ecs/log/log_test.go
cardinal/ecs/world.go

Doesn't close any ticket. 
Changes the logging a bit to add higher resolution timing measurement to the flush of the tick to redis. FinalizeTick does some extra stuff like json deserialization. I want to take that out of the equation.

chore(cardinal): Brian/add higher res logs for redis io flush

---

CHANGELOG.MD
cardinal/ecs/storage/nonce_test.go
cardinal/ecs/storage/redis/keys.go
cardinal/ecs/storage/redis/nonce.go
cardinal/ecs/world.go
cardinal/server/server_test.go
cardinal/server/utils.go

Nakama can send in a series of correctly-signed transactions, but still have some of them fail. Cardinal verifies that nonce values are used at most once by making sure each nonce value is strictly bigger than the last accepted nonce. If network hiccups cause the transaction requests to come in out of order, Cardinal will reject a transaction because the nonce is too small.
This fix uses a redis set to keep track of every seen nonce. This has storage implications; every transactions that will come in  will take up some memory in redis.
Since we launched we've processed about 151134 transactions (that's the current nonce value). If we call that 160,000 transactions, and we want DF to run for 2 weeks, that's approximately 2,240,000 nonces.
**Caveats**
[This redis …

fix(cardinal): Use a redis set to keep track of which nonces were used

---

.golangci.yaml

removes the linter that requires a period at the end of comments

ci: remove godot linter

---

CHANGELOG.MD
cardinal/ecs/ecb/tick.go
cardinal/ecs/ecb/tick_test.go
cardinal/ecs/log/log_test.go
cardinal/ecs/store/iface.go
cardinal/ecs/world.go

Closes: WORLD-668
Use a zerolog.Event to log tick timing information into a single log line.
Really, this timing information should be exported using a statsd metric, and not a log line, but custom metrics aren't yet set up for cardinal. See: See WORLD-669 and WORLD-671.
Updated unit tests

perf(cardinal): Log tick timing information into a single log line

---

relay/nakama/allowlist.go
relay/nakama/allowlist_test.go
relay/nakama/main.go
relay/nakama/save.go
relay/nakama/util_test.go

Add more unit tests for the allowlist code using the mock framework.
Rename the checkVerified to isUserVerified to make it more explicit when a user is and is not verified. Now, an error is only returned if there was a problem accessing the user's data.
Unit tests added. Use `go test`

test(nakama): Add more nakama unit tests using mocks

---

evm/scripts/start-sequencer.sh

default addr doesn't work, need to update it via sed.

fix(evm): add sed command to replace cometBFT API address with working address

---

CHANGELOG.MD
cardinal/ecs/ecb/doc.go
cardinal/ecs/ecb/ecb.go
cardinal/ecs/ecb/ecb_test.go
cardinal/ecs/ecb/read_only_test.go
cardinal/ecs/ecb/recovery_test.go
cardinal/ecs/ecb/redis_test.go
cardinal/ecs/ecb/tick.go

Closes: WORLD-653
There were two ways to commit pending ECB changes to redis. FinalizeTick and CommitPending. CommitPending would call "DiscardPending" after saving data to redis, meaning subsequent calls to CommitPending would only include changes that were made since the last call to CommitPending.
FinalizeTick, on the other hand, didn't call DiscardPending. Every time FinalizeTick was called, ALL previous changes would be re-submitted to redis. This includes data that wasn't actually modified.
This PR 1) Calls DiscardPending at the end of FinalizeTick and 2) Removes CommitPending completely (so there is only 1 way to save data to redis).
- Remove CommitPending
- Update tests to use FinalizeTick instead of CommitPending
- Add a test to ensure FinalizeTick execution times and memory …

fix(cardinal): Fix memory leak in ECB and remove CommitPending

---

cardinal/ecs/options.go
cardinal/ecs/world.go
cardinal/events/events.go
cardinal/testutils/testutils.go
cardinal/world.go

style(cardinal): use `New` prefix in EventHub constructors

---

docs/cardinal/loop.mdx

fixes an issue with loop page. quote block messed up

docs: fix loop page

---

cardinal/cardinal_test.go
cardinal/component_test.go
cardinal/ecs/lazycontainer.go
cardinal/ecs/lazysearch.go
cardinal/ecs/world.go
cardinal/ecs/world_context.go
cardinal/entity_test.go
cardinal/query_test.go
cardinal/search.go
cardinal/search_test.go
cardinal/system_test.go
cardinal/world_context.go

Closes: WORLD-699
Created a new search entity called `LazySearch` which holds something called a `LazyContainer` which holds `Search`
`LazySearch` acts very similarly to `Search` except when you instantiate `LazySearch` with the associated New method, it does not return an error. This error is forward to occur on the method calls as stated in the title.

feat(cardinal): Delay error of building a search query to happen on the Each, Count, First, and MustFirst method calls. 

---

cardinal/ecs/cql/cql.go
cardinal/ecs/ecb/ecb.go
cardinal/ecs/ecb/read_only.go
cardinal/ecs/filter.go
cardinal/ecs/filter/all.go
cardinal/ecs/filter/and.go
cardinal/ecs/filter/contains.go
cardinal/ecs/filter/exact.go
cardinal/ecs/filter/filter.go
cardinal/ecs/filter/filter_test.go
cardinal/ecs/filter/helper.go
cardinal/ecs/filter/not.go
cardinal/ecs/filter/or.go
cardinal/ecs/state_test.go
cardinal/types/component/component_test.go
cardinal/types/component/utils.go

Closes: WORLD-707
This is PR 1 out of 2 to refactor the Search system. This PR is focused on refactoring
`filter.ComponentFilter` to work wih `component.Component` instead of `component.ComponentMetadata`.
By doing this, we will be able to make `filter.ComponentFilter` the main way to do filter throughout
the codebase. 
- Refactor ComponentFilter to take in component.ComponentMetadata
- Minor adjustment to CQL to accomodate this new change
- Minor adjustment to tests to accomodate this new change
- Existing unit tests have been adjusted to accomodate this change

refactor(cardinal): make ComponentFilter use component.Component

---

relay/nakama/allowlist/allowlist.go
relay/nakama/allowlist/allowlist_test.go
relay/nakama/main.go
relay/nakama/mocks/mock_Match.go
relay/nakama/persona/persona_tag_verifier.go
relay/nakama/receipt/dispatcher.go
relay/nakama/receipt/notifications.go
relay/nakama/save.go

Closes: WORLD-740
This PR breaks allowlist functionality into it's own package, and add `notifications.go` alongside `dispatcher.go` to the `receipt` package. 
Please note that there is an upcoming PR via [WORLD-739](https://linear.app/arguslabs/issue/WORLD-739/locate-and-refactor-all-nakama-endpoints-to-be-in-the-same-place) that will refactor allowlist endpoint related code into `rpc.go` separately.
No new tests required, existing tests passing.

refactor(nakama): isolate allowlist and notifications

---

cardinal/ecs/engine.go
cardinal/world.go

previously, World would be responsible for setting up the event hub if engine didn't have one. this PR moves the responsibility to engine.

refactor(cardinal): make Engine responsible for defaulting the EventHub

---

cardinal/component_test.go
cardinal/ecs/ecs_test.go
cardinal/ecs/engine.go
cardinal/ecs/engine_test.go
cardinal/ecs/entity.go
cardinal/ecs/filter/filter_test.go
cardinal/ecs/search_test.go
cardinal/entity_test.go
cardinal/query_test.go
cardinal/search_test.go
cardinal/types/component/component_test.go

Closes: WORLD-752
before this PR, we had a delayed error of disallowing entity creation before loading game state.
this PR makes that assertion stronger, by erroring IMMEDIATELY if the state is not loaded. 
also removes an unused function.

refactor(cardinal): stronger assertion of disallowing entity creation before loading game state

---

cardinal/ecs/engine.go
cardinal/server/server.go
cardinal/server/server_test.go
cardinal/server/swagger.yml
docs/cardinal/openapi.json
docs/cardinal/rest/debug-state.mdx
docs/client/rest/debug-state.mdx

Our swagger.yml file describes the endpoints our cardinal server should expose. Some of those endpoints have variables in them (e.g. custom queries and message), but some endpoints should ALWAYS exist.
This newly added test verifies that the non-variable endpoints are actually created, have the correct method attached to them, and fixes some errors in our code base.
The biggest change here is going from "/debug/state" -> "/query/debug/state". If we're OK with this change, I need to also update the relevant docs.
Newly added unit tests verifies the swagger endpoints actually get created.

fix(cardinal): Make sure the endpoints declared in swagger are actually created

---

cardinal/cardinal_test.go
cardinal/ecs/ecs_test.go
cardinal/ecs/engine.go
cardinal/ecs/options.go
cardinal/events/events.go
cardinal/events/events_test.go
cardinal/option.go
cardinal/option_test.go
cardinal/server/handler/events.go
cardinal/server/server.go
cardinal/server/server_test.go
cardinal/testutils/world.go
cardinal/world.go

Closes: WORLD-753
This PR cleans up the dependency injection surface area to server to avoid dependency injecting the entire EventHub, which led to tight coupling between the two modules. Additionally, this PR also remove the EventHub interface and the EventHubLogger in favor of just using websocket mocks for I/O instead of using polymorphic EventHub.
- Replace EventHub dependency injection to server with just the websocket connection
- Cleans up the server router /events handler to make it consistent with the rest
- EventHub constructor now returns a pointer, making it consistent with server and engine.
- Some method/property renaming in EventHub
- All existing tests passes

refactor(cardinal): cleanup server <> event hub interaction

---

.github/workflows/build.yml
.github/workflows/lint-go.yml
.github/workflows/lint-pr-title.yml
.github/workflows/release.yaml
.github/workflows/starter-template-sync.yaml
.github/workflows/test.yml

Closes: DEVOP-169
- Cleaning up and updating CI action dependencies.
- Fix container release behavior: only on tags
- Remove Go action/cache -- enable default cache on new actions/setup-go@v5
- docker/setup-buildx-action `@v2` --> `@v3`
- actions/setup-go `@v4` --> `@v5`
- amannn/action-semantic-pull-request `@v5.1.0` --> `@v5.4.0`
- ScribeMD/docker-cache `@0.3.4` --> `@0.3.7`
- cpina/github-action-push-to-another-repository `@main` --> `@v1.7.2`
- remove Go actions/cache@v3 -- replaced by default cache on actions/setup-go@v5
- changes release condition to only on tags ( `'evm/v*.*.*' , 'relay/nakama/v*.*.*'` )
- All CI checks pass.

ci: cleaning up and update CI action dependencies.

---

cardinal/server/server.go

quick pr after i noticed config was exported when it didn't need to be

chore(cardinal): make server.Config unexported

---

cardinal/config.go
cardinal/config_test.go
cardinal/world.go

moving some validation logic of the config to `config.go`.

refactor(cardinal): move config validation to config.go

---

relay/nakama/allowlist_test.go
relay/nakama/signer/nakama_test.go
relay/nakama/testutils/testutils.go

Closes: WORLD-808
Create a "fake" version of NakamaModule and use it in some tests.
The fake implementation uses a map to store information. It's suitable for tests that write and read information to the DB and do not use any search functionality or versioning functionality.
This allows us to write tests that focus on public facing methods (i.e. rpc handlers). In addition, the sequence of database reads and writes don't need to be known ahead of time. Tests also look cleaner because the setup code only uses the public facing methods.
Unit tests have been modified to use the fake implementation. Some tests have been expanded to cover more edge cases.

test(nakama): Make a fake version of nakama module and update some tests

---

starter-game-template/docker-compose.yml
starter-game-template/world.toml

Closes: WORLD-726
Expose `ENABLE_ALLOWLIST` env variable through world.toml
- add `ENABLE_ALLOWLIST` to nakama docker env
- add `ENABLE_ALLOWLIST` field to world.toml

chore: add nakama beta key option to world toml

---

relay/nakama/cardinal.go
relay/nakama/handlers.go
relay/nakama/main.go
relay/nakama/persona/verifier.go
relay/nakama/receipt/dispatcher.go
relay/nakama/receipt/dispatcher_test.go
relay/nakama/receipt/notifications.go
relay/nakama/receipt/notifications_test.go
relay/nakama/rpc.go

Closes: WORLD-741
There are several global vars at the top of our nakama plugin's `main.go` file. We create these global vars locally now and pass them in as params to the functions that need them instead.
- No new tests, existing tests passing.

refactor(nakama): break global vars into local vars and pass in as params

---

docs/cardinal/game/world/api-reference.mdx

updates the typo in the docs that uses the wrong option name for setting TickChannel.

docs: use correct function name for setting TickChannel WorldOption

---

cardinal/world.go
cardinal/world_context.go

`NewWorldContextForTick` is a public function when it's intended only for internal use. This PR makes the function private.
- Make NewWorldContextForTick private
- N/A

refactor(cardinal): make NewWorldContextForTick private

---

CODEOWNERS

I propose we remove CODEOWNERS that assigns everyone/anyone to review a PR. I don't think this is working for the following reason:
The current process makes PR review slower
There is ambiguity on who is responsible for reviewing a certain PR when everyone thinks "oh its fine someone else will review the PR". In reality, everyone thought the same thing, so no PR gets reviewed.
It's very spammy on github notifs, which creates tendency for people to ignore GH notifications altogether -> making PR review slower.
The current process implies that anyone's PR review is ok, resulting with PRs getting merged with low quality reviews (i.e. feature PRs getting merged despite not fulfilling the feature requirement, implementations ignoring existing established code patterns, etc). …

chore: remove CODEOWNERS

---

.golangci.yaml
cardinal/cql/cql.go
cardinal/plugin_cql.go

defines the GetComponentByName dependency explicitly, so we dont type out the function signature multiple times
removes unused structs

chore(cardinal): remove unused structs in CQL, define component getter function as type

---

docs/cardinal/game/cql.mdx

Some of the examples used `CONTAIN` instead of `CONTAINS`.

docs: typos on cql queries

---

cardinal/cardinal.go
cardinal/cardinal_test.go

Closes: WORLD-885
- new function `EachMessage[In any, Out any](wCtx, fn func().....)`
- changed unit test to use EachMessage
This design proposal was suggested by @jerargus. 
Basically during his proposal I didn't realize how simple it would be to implement. It's actually a feature change that only needs to go on top of our existing changes. It's actually a trivial change. 
Overall this change should replace MessageType usage in systems all together and reduce the amount of code a user uses. The downside of this change is that it becomes a bit inconsistent with our usage of Each. We now have Each methods everywhere and suddenly for Messages we have an EachMessage thing which isn't even a method but a function out of nowhere. 
It makes it inconsistent with Components especially. 
This PR …

feat(cardinal): EachMessage design proposal

---

cardinal/log/log.go

Closes: WORLD-890
The array of components in this log was in a random order because map iteration was used to generate it. 
Code has been updated to ensure components are logged in ascending ID order. 
An alternative fix here would be to update the test to ignore out-of-order components, however I think making sure the components are in a predicable order (as well as the order that they were registered) is useful.
from world-engine/cardinal/log run:
`go test -run=TestWorldLogger --count=20`

fix(cardinal): Fix flaky TestWorldLogger

---

.github/workflows/docs-preview.yml
.github/workflows/lint-go.yml
.github/workflows/starter-template-sync.yaml
.github/workflows/test.yml

- bump ci action version
- optimize namespace runner usage (minimize ci queue)
- fix docs preview instruction failed on main branch

ci: nits bump version, optimize runner, fix docs preview instruction

---

cardinal/cardinal.go
cardinal/cardinal_test.go
cardinal/engine_test.go
cardinal/example_messagetype_test.go
cardinal/plugin_persona.go
cardinal/plugin_receipt_test.go
cardinal/server/server_test.go
cardinal/state_test.go
cardinal/testutils/message.go
cardinal/tick_test.go
cardinal/world_context.go
e2e/testgames/game/sys/join.go
e2e/testgames/game/sys/move.go

Closes: WORLD-888
- `GetMessage` is made private, and will after this be referred to as `getMessage`.
- `getMessage` is moved to `cardinal.go`
- `EachMessage` is used in unit tests where it is relevant
- `testutils.GetMessage` is created and it's a copy of `cardinal.getMessage`. `testutils.GetMessage` is to be used in unit tests.
- edit: getMessage has been removed. The logic is inlined into `EachMessage`. There is now only one `GetMessage` function and it lives in testutils.

feat(cardinal): MessageEach refactor finalization.

---

cardinal/server/server.go
cardinal/world.go

Closes: WORLD-896
- Minor enhancement for Railway-related deployment usecase
- GoFiber by default only listen to tcp4 (ipv4), change that to listen on both tcp4 & tcp6 (Railway private networking only support ipv6) https://docs.railway.app/guides/private-networking#listen-on-ipv6
- Increase Redis conn dial timeout at startup to 15 seconds, there was a flaky startup connection encountered when deploying on Railway -- most likely caused by network initialization delay
- This change is a trivial rework/code cleanup without any test coverage.

feat: enable go-fiber tcp4 & tcp6 server, increase Redis conn dial timeout (Railway-related enhancement )

---

cardinal/message/message.go
cardinal/query.go
cardinal/router/router_test.go
cardinal/server/docs/docs.go
cardinal/server/docs/swagger.json
cardinal/server/docs/swagger.yaml
cardinal/server/handler/debug.go
cardinal/server/server.go
cardinal/server/server_test.go
cardinal/types/engine/query.go
cardinal/types/message.go
cardinal/types/util.go
cardinal/world.go

Closes: WORLD-876
Add GET endpoint `/debug/world` that provides detail of components, messages, queries
- added 1 enpointd GET `/debug/world`
- added func to get field detail using reflect
- added unit test
- test run using sgt and got this response
```
{
"components": [
"SignerComponent",
"Player",
"Health"
],
"messages": [
{
"name": "attack-player",
"fields": {
"TargetNickname": "string"
}
},
{
"name": "create-persona",
"fields": {
"PersonaTag": "string",
"SignerAddress": "string"
}
},
{
"name": "authorize-persona-address",
"fields": {
"Address": "string"
}
},
{
"name": "create-player",
"fields": {
"Nickname": "string"
}
}
],
"queries": [
{
"name": "signer",
"fields": {
"PersonaTag": "string",
"Tick": "uint64"
}
},
{
"name": "state",
"fields": {}
},
{
"name": "cql",
"fields": {
"CQL": …
```

feat(cardinal): add endpoint that provides detail of components, messages, queries

---

cardinal/component/component_test.go
cardinal/filter/contains.go
cardinal/filter/exact.go
cardinal/filter/helper.go
cardinal/state_test.go

Closes: WORLD-878
Search is bounded by this:
O(ACF)
if A == C == F == N then the upper bound is O(N^3)
This change mitigates the runtime to O(N^2) by saving it to a map. For small N this change is actually slower slightly. For large N this change is significantly faster. A future PR can have the system detect the length of the query and the length of the amount of components and dynamically decide on linear search or map. 
Overall though this is just a slight change as cacheing takes over after the first time Each is called on a search. This just decreases start up time and new searches that aren't cached. For a large amount of archetypes, components and large queries the slow down can hiccup and block the main loop. 
There is an alternative implementation here where on EXACT and …

perf(cardinal): faster search.

---

docker-compose.yml
e2e/testclients/e2etestclient/Dockerfile
e2e/testclients/e2etestclient/testsuite_test.go

Closes: WORLD-780
- Part of this PR https://github.com/Argus-Labs/world-engine/pull/650, adding redis-cli tools to E2E test container
- install redis-tools to container
- adjust redis flush command

fix(e2edb): add redis-tools to test_nakama container

---

docker-compose.yml
makefiles/test.mk

Closes: WORLD-928
This is a simple change that uses `docker compose down -v` to shutdown all the containers at the end of each nakama e2e test run and delete their volumes. This means each new run will start with clean state but also will not require any image redownloading.

fix(e2e): clean all containers at the end of e2e test rounds

---

.github/codecov.yml

Closes: WORLD-926
- As mentioned by @pyrofolium , there has been a significant drop in code coverage after upgrading the Go version to 1.22, particularly affecting the `relay/nakama` package.
- It appears that the change in code coverage is not directly related to the Go upgrade. However, I've noticed that the code detected by coverage tools in the `relay/nakama` package has drastically changed. It's unclear whether this is a bug or if there is some cached data causing the issue.
- One of the major jumps in coverage comes from the generated mocks package, which should have been filtered out
Before:
After:
^^ There's 9000 new tracked lines from generated mocks packages alone
- Filter out generated mocks files

ci: fix relay/nakama code coverage 

---

cardinal/cardinal.go
cardinal/cardinal_test.go
cardinal/engine_test.go
cardinal/persona/persona_test.go
cardinal/plugin_debug.go
cardinal/plugin_persona.go
cardinal/plugin_receipt.go
cardinal/plugin_receipt_test.go
cardinal/query/manager.go
cardinal/query/query.go
cardinal/query/query_test.go
cardinal/server/server_test.go
cardinal/state_test.go
cardinal/tick_test.go
cardinal/world.go
cardinal/world_recovery_test.go
e2e/testgames/game/query/location.go

Move all the query business logic to a `query` package with the manager pattern. This places the final key piece on the cardinal package refactor.
- Creates `query` package with a manager that manages query registrations
- Extract `queryToName` and `registeredQueries` struct from World and consolidates them to `registerQueries` map in the `query.Manager` struct.
- Move `cardinal/query.go` and `cardinal/query_test.go` to `/cardinal/query/...`
- [Breaking] `cardinal.WithQueryEVMSupport` is now `query.WithQueryEVMSupport` similar to message
- All existing test passes

refactor(cardinal): move query business logic to manager

---

cardinal/cardinal.go
cardinal/message/manager.go
cardinal/message/message.go
cardinal/message/message_test.go

There is a lot of inconsistency with how the message manager is implemented with the rest of the managers (query, system, etc). This refactor fixes on of them.
- Eliminate the bulk message registration from the message manager, which will never be used anyway.
- Eliminate the generics `RegisterMessageWithManager` function that is inconsistent with the rest of the manager registration pattern.

refactor(cardinal): eliminate generics from message registration to manager

---

cardinal/server/server_test.go
cardinal/testutils/testutils.go
cardinal/world.go

Self explanatory, for naming consistentcy
- Rename ListMessages -> GetRegisteredMessages
- Rename ListQueries -> GetRegisteredQueries
- N/A

refactor(cardinal): rename ListMessages/Queries to GetRegisteredMessages/Queries

---

cardinal/cardinal_test.go
cardinal/engine_test.go
cardinal/server/handler/tx.go
cardinal/server/server.go
cardinal/server/server_test.go
cardinal/server/types/provider.go
cardinal/types/engine/context.go
cardinal/world.go
cardinal/world_context.go

Right now we are using `engine.Context` as an omnibus way to pass around random stuff from World throughout the codebase that significantly explodes its surface area.
This refactor contains the first cut refactor to use the provider pattern, which allows us to eliminate `UseNonce` from `engine.Context` 
- Create Provider for package `server` that expose world functionality that it needs
- Remove `UseNonce` from `engine.Context`
- `world.Namespace()` now returns string type
- N/A

refactor(cardinal): refactor server to use provider pattern

---

cardinal/server/option.go
cardinal/world.go

This PR removes the server `WithPrettyPrint` option since the `log.Logger` would only need to be overwritten once from world.go. Additionally, this reorders a log to make sure its pretty printed.
- Remove `server.WithPrettyPrint`
- Reorder bootup sequence logs in `cardinal.NewWorld`
- N/A

refactor(cardinal): clean up logs pretty printing

---

cardinal/world.go
cardinal/world_context.go

This PR removes `GetMessageManager` that exposes an internal private struct field which leads to abstraction violation.
- Remove `GetMessageManager`
- N/A

refactor(cardinal): remove GetMessageManager

---

cardinal/cardinal_test.go
cardinal/gamestate/ecb.go
cardinal/gamestate/manager.go
cardinal/log/log_test.go
cardinal/option.go
cardinal/option_test.go
cardinal/world.go
cardinal/world_context.go
cardinal/world_test.go

This PR removes `World.Logger` and `EntityCommandBuffer.Logger` in favor of using the global logger provided via `log.Logger`. World options will now overwrite the global logger instead.
This is done to ensure better consistency of log configuration and eliminate the need to needlessly dependency inject the logger across the codebase.
- Remove `World.Logger` struct field
- Remove `EntityCommandBuffer.Logger` struct field
- Remove `World.InjectLogger`
- Added `cardinal.WithCustomLogger` to overwrite the global logger configuration used
- `cardinal.WithPrettyLog` now overwrites `log.Logger`
- Test adjusted accordingly.

refactor(cardinal): use global logger

---

cardinal/cardinal_test.go
cardinal/engine_test.go
cardinal/option.go
cardinal/world.go
cardinal/world_recovery_test.go

This PR removes `world.SetRouter` in favor of `WithCustomRouter` option which is consistent with the existing pattern, which also avoid violating the abstraction boundaries.
- Remove `SetRouter`
- Adds `WithCustomRouter` option for injecting a custom router to World
- Tests updated accordingly

refactor(cardinal): replace world.SetRouter with an option

---

evm/go.mod
evm/go.sum
go.work.sum

apparently adding prints to polaris EVM's PrepareProposal prevents some sort of race condition that was causing a panic?? idk. it doesnt panic anymore though ??? at the cost of some ugly logs but ill take it..

chore(evm): bump version of forked polaris EVM

---

.github/workflows/test.yml
cardinal/server/docs/docs.go
cardinal/server/docs/swagger.json
cardinal/server/docs/swagger.yaml
cardinal/server/handler/cql.go
cardinal/server/handler/tx.go
makefiles/test.mk

Closes: WORLD-925
Do Swagger specs check to make sure it doesn't change.
- Add `make swagger-check`: perform a diff check between the existing and newly generated swagger specs from the latest changes.
- Add `make swaggo-install`: install swag-cli to generate swagger specs files.
- Add CI action to execute swagger-check on PR event. 
- Fix swaggo annotation issue on function with multiple API operations (`cardinal/server/handler/tx.go`, `PostTransaction`) 
--> Swaggo supports multiple `@Router` on a single function, but multiple defined annotations like `@Summary`, and `@Accept`,`@Produce` with same value causing a double and overridden and invalid swagger specification format. 
(I put the details in the review comments below https://github.com/Argus-Labs/world-engine/pull/698#discussion_r …

ci: add swagger check

---

cardinal/server/handler/world.go
cardinal/server/server.go
cardinal/server/server_test.go

Closes: WORLD-976
Add cardinal namespace to /world endpoint
- modify return value and param for GetWorld func
- Adjust unit test to assert namespace
- Manually test the result
```
{
"namespace": "world-1",
"components": [
{
"name": "SignerComponent",
"fields": {
"AuthorizedAddresses": "[]string",
"PersonaTag": "string",
"SignerAddress": "string"
}
},
{
"name": "Player",
"fields": {
"Nickname": "string"
}
},
{
"name": "Health",
"fields": {
"HP": "int"
}
}
],
"messages": [
{
"name": "create-persona",
"fields": {
"PersonaTag": "string",
"SignerAddress": "string"
},
"url": "/tx/persona/create-persona"
},
{
"name": "authorize-persona-address",
"fields": {
"Address": "string"
},
"url": "/tx/game/authorize-persona-address"
},
{
"name": "create-player",
"fields": {
"Nickname": "string"
},
"url": …
```

feat: add namespace to /world endpoint

---

cardinal/search/search.go
cardinal/search/search_test.go

Closes: WORLD-617
this allows users to use search like this with chained filters:
```go
amount, err = cardinal.NewSearch(worldCtx, filter.Exact(Alpha{})).
FilterSelect(func(id types.EntityID) bool {
comp, err := cardinal.GetComponent[Alpha](worldCtx, id)
assert.NilError(t, err)
return comp.Name1 == "BLAH"
}).Count()
```
FilterSelects can be chained on top of a Search object an unlimited amount of times. This brings the search api more inline with functional programming paradigms where we have map, reduce, filter, and foreach. With golang, only filter and foreach are possible as chainable methods. Map/Reduce will require functions as they are generic. 
The secondary purpose for adding this feature is to pave the way for filters to be a compile target for High level CQL syntax that allows …

feat(cardinal): add property filtering capabilities to search.

---

docs/client/nakama/relay.mdx

Add a section to the "Game Engine/Client Integration" page to describe how to get receipts and events from Nakama.
As well as unity examples.
I intend to test this with @darkmavis to ensure it's proper unity code.

docs(nakama): add docs for viewing receipts and events

---

.github/workflows/lint-go.yml
.golangci.yaml
cardinal/component/component_test.go
cardinal/ecs_test.go
cardinal/errors_test.go
cardinal/example_messagetype_test.go
cardinal/option.go
cardinal/option_test.go
cardinal/server/event_test.go
cardinal/state_test.go
cardinal/system/manager.go
cardinal/testutils/world.go
cardinal/tick_test.go
cardinal/world.go
cardinal/world_test.go
makefiles/ci.mk

This PR cleans up the way we are we are using miniredis in the hope of fixing the flaky test.
- Remove `NewMockWorld` in favor of using a `WithMockRedis` option
- Let miniredis cleans up itself after tests using `miniredis.RunT(...)`
- Remove `World.cleanup` since we no longer have a use for it 
- Remove `TestSchemaChecking` as it does the same thing with `TestRegisterComponent_ErrorOnSchemaMismatch`
- `make lint` improvements
- Check if the correct version of the linter is already before trying to install again
- Remove the concurrency declaration that is preventing the CI from using all cores
- Add `lint-cardinal` for scoped linting 
- Updated tests accordingly

refactor(cardinal): clean up mock redis flow

---

cardinal/server/event_test.go

TestEventsThroughSystems is flaky and I'm unable to reproduce the failure locally. In CI, the failure is identified by a test timeout after 10 minutes. I believe the reason for the hang is because assert.NilError kills the containing goroutine, so an event in the system is never emitted, causing `mode, message, err := dialer.ReadMessage()` to block forever.
I can reproduce the timeout by manually changing the EmitEvent error to non-nil.
assert.Check is allowed to be called from a non-main goroutine, but assert.NilError does not have that same guarantee.
By changing these assertions to assert.Check, this test will fail right away instead of timing out.
Note, this is NOT a fix for the flaky test. Instead it will 1) Ensure the flake test fails faster and 2) hopefully give us an error message …

test(cardinal): Ensure this flaky test fails faster instead of timing out after 10 minutes

---

cardinal/cardinal_test.go
cardinal/testutils/testutils.go

removes a utils function that isn't needed. the testfixture has a method that handles the same thing. found it lingering around while working on nonce PR.

chore(cardinal): remove extra utils function

---

cardinal/server/docs/docs.go
cardinal/server/docs/swagger.json
cardinal/server/docs/swagger.yaml
cardinal/server/handler/query.go
cardinal/server/handler/tx.go

Closes: WORLD-1039
Since the message/query group is variable (through `WithCustomMessageGroup`/`WithCustomQueryGroup`), the swagger docs should show this.
Manual verification

docs(cardinal): use {custom-group} instead of 'game' in query/tx endpoints

---

cardinal/server/docs/docs.go
cardinal/server/docs/swagger.json
cardinal/server/docs/swagger.yaml
cardinal/server/handler/query.go
cardinal/server/handler/tx.go

Add back `/tx/game/{txName}` & `/query/game/{queryName}` endpoints.
Manually verified

docs(cardinal): add default message/query group route in swagger

---

.github/workflows/lint-md.yml

Lock eslint & eslint-plugin-mdx linter package version, latest v8 --> v9 (5 April) introduce breaking changes with the CLI & config file.
- lock version package eslint @8.57.0
- lock version package eslint-plugin-mdx @3.1.5
- Linter CI passed

ci: lock eslint linter package version

---

cardinal/tick_results.go
cardinal/types/engine/context.go
cardinal/world_context.go

adding back the ability to emit an event via string. this is for backwards compat for marks current code. and possibly others.
- adds EmitStringEvent to both world context as well as TickResults

feat(cardinal): add emit string event

---

e2e/testgames/game/sys/join.go
e2e/tests/nakama/nakama_test.go
relay/nakama/main.go

Closes: WORLD-1011
Previously, a non-json encoded string event would result in a json.Unmarshal error, which was then ignored.
Now when we encounter an error, the string is wrapped in a `{"message": "<the event>"}` json blob.
The e2e game has been adjusted to emit both a map event and a string event. The relevant test has been updated to check for both strings.

fix(nakama): Jer/world 1011 string events should be wrapped in json

---

cardinal/receipt/receipt.go
cardinal/receipt/receipt_test.go
e2e/tests/nakama/nakama_test.go
makefiles/test.mk
relay/nakama/main.go

Ensure failing e2e tests will properly fail CI. Fix broken e2e tests.
- Add the `set -o pipefail` prefix to a make command to ensure the pipe does not swallow test errors
- Fix a broken cql test (the cql endpoint was moved from query/game/cql to just cql)
- Fix a broken receipts test (receipt errors were not converted to strings before being sent across the wire)
`make e2e-nakama` to run the end to end tests locally.

fix(cardinal): Jer/ensure e2e tests fail ci

---

cardinal/gamestate/redis.go
cardinal/gamestate/redis_test.go

Closes: WORLD-1010
compValuesToDelete keeps track of what entity/components need to be deleted from redis. Previously, this store was never cleared out between ticks. Consequently, if component X is delete on tick 10, every tick after 10 would also get a redis command to delete that component X. 
This set of components to delete would grow without bounds and cause the finalize tick portion of the tick to increase over time.
Ensure compValuesToDelete is cleaned up between ticks. 
Add a test to ensure the struct is empty between ticks.
Unit test added.

fix(cardinal): Ensure components to delete are cleared between ticks

---

cardinal/plugin_persona.go
cardinal/world_persona_test.go

Previously, these persona-tag related systems would build an index of every persona-tag -> signer address every single tick. If no persona-tag related messages were present, this index would go unused.
With this modification, these persona-tag -> signer address map will only be built if it's actually going to be used.
Unit test added. It ensures the persona-tag related systems don't slow down significantly when no persona-tag messages need to be processed.

perf(cardinal): Only rebuild the persona tag index when needed

---

cardinal/cardinal.go
cardinal/errors_test.go
cardinal/persona/persona_test.go
cardinal/query.go
cardinal/query_manager.go
cardinal/query_test.go
cardinal/world.go

Closes: WORLD-1125
Query storage used to be inconsistently implemented with an index based on group/name with storage based on name only. 
This PR completely converts query storage into a map[group][name] storage. 
The cost of this is that the API can no longer have a QueryByName, you need to have the group explicitly declared to fetch a query.

refactor(cardinal): switch query storage to use groups.

---

cardinal/cardinal_test.go
cardinal/state_test.go
cardinal/testutils/testutils.go
cardinal/util.go

Closes: WORLD-1124
Moved GetMessage to testutils. In order to use "private" functionality changed the signature of this to use world instead of Wctx.

refactor(cardinal): move GetMessage to testutils.

---

relay/nakama/auth/siwe.go

Send the message of the error causing the SIWE error instead of "missing message".

feat: better error message for siwe auth errors

---

cardinal/gamestate/doc.go

Closes: WORLD-864
trivial change to docs. Just folliowing the ticket here: 
https://linear.app/arguslabs/issue/WORLD-864/package-gamestate-references-ecb-in-docgo-rename-back-to-ecb-or-update

refactor(cardinal): update docs of ecb pagkage o gamestate package

---

cardinal/server/debug_test.go
cardinal/server/docs/docs.go
cardinal/server/docs/swagger.json
cardinal/server/docs/swagger.yaml
cardinal/server/handler/debug.go
cardinal/server/types/provider.go
cardinal/types/entity.go
cardinal/world.go

Closes: WORLD-1146
Cardinal editor breaking because the response format of `/debug/state` endpoint is changed.
This PR is to revert the changes.
From : 
```
type EntityStateElement struct {
ID   EntityID          `json:"id"`
Data []json.RawMessage `json:"data" swaggertype:"object"`
}
```
To :
```
type DebugStateElement struct {
ID         EntityID                   `json:"id"`
Components map[string]json.RawMessage `json:"components" swaggertype:"object"`
}
```
- Add new `DebugStateElement` types entity for response
- Change the response using `DebugStateElement` struct
- Adjust the unit test and swagger
- Adjusted Unit Test
- Tested manually using Cardinal Editor v0.4.0
- Tested manually using Postman
Sample Result :
```
[
{
"id": 0,
"components": {
"Health": {
"HP": 246
},
"Player": { …
```

fix: revert return of /debug/state endpoint from array to map

---

cardinal/engine_test.go
cardinal/world.go
cardinal/world_context.go

feat(cardinal): millisecond timestamp

---

relay/nakama/events/events.go

fix(nakama): log websocket connection retries as error
